{% set name="recentrifuge" %}
{% set version="1.3.1" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

source:
  url: https://github.com/khyox/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: e6cbe7ee5b2a8ec4586dbecf238c77c70f33fe59f7dce8f669d49ba87632ec02

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - biopython >=1.70
    - xlrd >=0.9.0
    - numpy >1.15
    - matplotlib-base >3.0
    - openpyxl >2.5.0
    - pandas >=0.23.2

test:
  commands:
    - rcf --version

about:
  home: https://github.com/khyox/recentrifuge
  license: 'GPLv3'
  license_file: LICENSE.txt
  summary: 'Robust comparative analysis and contamination removal for metagenomics'

extra:
  recipe-maintainers:
    - thanhleviet
  doi:
    - 10.1371/journal.pcbi.1006967
