{% set version = "1.0.2" %}
{% set sha256 = "c21a85a8ea2e4a88ff9fc6828ab08e1ed6f05fbf45c94951948a219f0467891a" %}

package:
  name: eukulele
  version: 1.0.2

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps"

source:
  url: https://github.com/AlexanderLabWHOI/EUKulele/archive/v1.0.2z.tar.gz
  sha256: {{ sha256 }}

test:
  commands:
    - EUKulele --version | grep '{{ version }}'
    - EUKulele --help

requirements:
  host:
    - python>=3.6
    - pip
    - pytest-runner
  run:
    - python>=3.6
    - numpy==1.19.0
    - biopython==1.77
    - pandas==1.0.5
    - seaborn-base==0.11.0
    - r-base==3.6.3
    - boost-cpp==1.70.0
    - chardet
    - joblib
    - ujson
    - pyyaml
    - matplotlib-base==3.3.1
    - blast==2.2.31
    - busco==4.0.6 
    - diamond==0.9.36

about:
  home: https://github.com/AlexanderLabWHOI/EUKulele
  license: MIT
  license_file: LICENSE
  summary: Easy taxonomic annotation for eukaryotic microbes
